name: rootnav2
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy=1.16.4
  - opencv=3.4.2
  - pillow=6.1.0
  - pip=19.1.1
  - py-opencv=3.4.2
  - python=3.6.8
  - pytorch=1.0.1
  - pyyaml=3.13
  - scipy=1.2.1
  - torchvision=0.2.2
  - yaml=0.1.7
  - tensorboardx=2.0=py_0
  - pydensecrf==1.0rc3
  - tensorboardx=2.0=py_0
  - pip:
    - cython==0.29.13
    - kdtree==0.16
    - matplotlib==2.2.2
    - pyparsing==2.4.1.1
    - tqdm==4.32.2
